server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true